import type { PantryProduct, PantryCollection } from "./pantry-catalog";
import { EVEREST_UNIT_COSTS } from "./everest-wholesale";
import { priceFromCost, type PricingRule } from "./staple-pricing";

const PLACEHOLDER = "/products/staples/placeholder.svg";

/** Downloaded pack shots — falls back to placeholder when missing. */
const HAS_IMAGE = new Set([
  "aashirvaad-atta-20lb",
  "basmati-rice-10lb",
  "besan-2kg",
  "chana-dal-10lb",
  "coriander-100g",
  "cumin-100g",
  "indian-pickle",
  "lays-chips",
  "maggi-noodles",
  "makhana",
  "masoor-dal-10lb",
  "moong-dal-10lb",
  "mustard-oil-1l",
  "nanak-ghee",
  "paneer",
  "papad",
  "parle-g-biscuits",
  "poha",
  "rajma-10lb",
  "rava-sooji-2kg",
  "red-label-tea",
  "salt-2kg",
  "sona-masoori-rice-10lb",
  "sugar-2kg",
  "sunflower-oil-1l",
  "toor-dal-10lb",
  "turmeric-100g",
  "urad-dal-10lb",
]);

function stapleImage(id: string): string {
  return HAS_IMAGE.has(id) ? `/products/staples/${id}.jpg` : PLACEHOLDER;
}

type CompetitorEntry = {
  store: string;
  price: number;
  unit: string;
};

type StapleSpec = {
  id: string;
  uuid: string;
  name: string;
  shortDescription: string;
  brand?: string;
  unit: string;
  cost: number;
  rule: PricingRule;
  pricingRole: "kvi" | "margin" | "mild-kvi";
  collection: PantryCollection;
  category: string;
  roleLine: string;
  whySelected: string;
  badges?: string[];
  competitors?: CompetitorEntry[];
};

function staple(s: StapleSpec): PantryProduct {
  const pricing = priceFromCost(s.cost, s.rule);
  return {
    uuid: s.uuid,
    id: s.id,
    slug: s.id,
    name: s.name,
    shortDescription: s.shortDescription,
    longDescription: s.shortDescription,
    category: s.category,
    collection: s.collection,
    image: stapleImage(s.id),
    imageAlt: s.name,
    unit: s.unit,
    stock: 50,
    ...pricing,
    competitors: s.competitors ?? [],
    brand: s.brand,
    origin: "India",
    pantry: {
      roleLine: s.roleLine,
      audience: ["Family"],
      badges: s.badges ?? [],
      whySelected: s.whySelected,
      pricingRole: s.pricingRole,
      ingredientSections: [{ rows: [{ name: "See package label" }] }],
      nutritionHighlights: "See package label.",
      preparation: "See package label.",
      storage: "Store in a cool, dry place.",
      countryOfOrigin: "India",
      gallery: [stapleImage(s.id)],
    },
  };
}

export const stapleProducts: PantryProduct[] = [
  staple({
    id: "aashirvaad-atta-20lb",
    uuid: "b2000001-0000-4000-8000-000000000001",
    name: "Aashirvaad Atta",
    shortDescription: "Whole wheat atta — 20 lb bag.",
    brand: "Aashirvaad",
    unit: "20 lb",
    cost: 16.79,
    rule: "kvi-near",
    pricingRole: "kvi",
    collection: "staples",
    category: "Flour & grains",
    roleLine: "India's #1 atta — weekly roti staple.",
    whySelected: "#1 price-memorized staple; priced near cost to win the basket.",
    badges: ["KVI"],
    competitors: [
      { store: "Walmart", price: 22.48, unit: "20 lb" },
      { store: "Swadesh", price: 24.29, unit: "20 lb" },
    ],
  }),
  staple({
    id: "basmati-rice-10lb",
    uuid: "b2000002-0000-4000-8000-000000000002",
    name: "Basmati Rice",
    shortDescription: "Premium branded basmati rice — 10 lb.",
    unit: "10 lb",
    cost: EVEREST_UNIT_COSTS.basmati10lb,
    rule: "kvi-thin",
    pricingRole: "kvi",
    collection: "staples",
    category: "Flour & grains",
    roleLine: "Long-grain basmati for biryani and everyday meals.",
    whySelected: "Price-memorized rice — thin margin hook.",
    badges: ["KVI"],
  }),
  staple({
    id: "sona-masoori-rice-10lb",
    uuid: "b2000003-0000-4000-8000-000000000003",
    name: "Sona Masoori Rice",
    shortDescription: "Everyday sona masoori rice — 10 lb.",
    unit: "10 lb",
    cost: 9.0,
    rule: "kvi-thin",
    pricingRole: "kvi",
    collection: "staples",
    category: "Flour & grains",
    roleLine: "High-frequency everyday rice.",
    whySelected: "High-frequency staple — thin margin to drive repeat visits.",
    badges: ["KVI"],
  }),
  staple({
    id: "toor-dal-10lb",
    uuid: "b2000004-0000-4000-8000-000000000004",
    name: "Toor Dal",
    shortDescription: "Split pigeon peas — 10 lb.",
    unit: "10 lb",
    cost: 18.19,
    rule: "kvi-thin",
    pricingRole: "kvi",
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Most-bought dal in Indian kitchens.",
    whySelected: "Most-bought dal — thin margin KVI hook.",
    badges: ["KVI"],
  }),
  staple({
    id: "masoor-dal-10lb",
    uuid: "b2000005-0000-4000-8000-000000000005",
    name: "Masoor Dal",
    shortDescription: "Red lentils — 10 lb.",
    unit: "10 lb",
    cost: EVEREST_UNIT_COSTS.masoor10lb,
    rule: "kvi-thin",
    pricingRole: "kvi",
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Quick-cooking everyday dal.",
    whySelected: "Common household dal — thin margin KVI.",
    badges: ["KVI"],
  }),
  staple({
    id: "urad-dal-10lb",
    uuid: "b2000006-0000-4000-8000-000000000006",
    name: "Urad Dal",
    shortDescription: "Split black gram — 10 lb.",
    unit: "10 lb",
    cost: 14.99,
    rule: "margin",
    pricingRole: "margin",
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Essential for dosa, idli, and dal makhani.",
    whySelected: "Background dal with healthy markup.",
  }),
  staple({
    id: "chana-dal-10lb",
    uuid: "b2000007-0000-4000-8000-000000000007",
    name: "Chana Dal",
    shortDescription: "Split Bengal gram — 10 lb.",
    unit: "10 lb",
    cost: 12.29,
    rule: "margin",
    pricingRole: "margin",
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Versatile dal for everyday cooking.",
    whySelected: "Background dal with healthy markup.",
  }),
  staple({
    id: "moong-dal-10lb",
    uuid: "b2000008-0000-4000-8000-000000000008",
    name: "Moong Dal",
    shortDescription: "Split green gram — 10 lb.",
    unit: "10 lb",
    cost: 14.99,
    rule: "margin",
    pricingRole: "margin",
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Light, easy-to-digest everyday dal.",
    whySelected: "Background dal with healthy markup.",
  }),
  staple({
    id: "rajma-10lb",
    uuid: "b2000009-0000-4000-8000-000000000009",
    name: "Rajma",
    shortDescription: "Kidney beans — 10 lb.",
    unit: "10 lb",
    cost: 17.59,
    rule: "margin",
    pricingRole: "margin",
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Classic rajma for Punjabi-style curries.",
    whySelected: "Background legume with healthy markup.",
  }),
  staple({
    id: "kabuli-chana-10lb",
    uuid: "b200000a-0000-4000-8000-00000000000a",
    name: "Kabuli Chana",
    shortDescription: "Chickpeas — 10 lb.",
    unit: "10 lb",
    cost: 8.99,
    rule: "margin",
    pricingRole: "margin",
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Chole and chaat staple.",
    whySelected: "Background legume with healthy markup.",
  }),
  staple({
    id: "besan-2kg",
    uuid: "b200000b-0000-4000-8000-00000000000b",
    name: "Besan",
    shortDescription: "Gram flour — 2 kg.",
    unit: "2 kg",
    cost: 5.5,
    rule: "margin",
    pricingRole: "margin",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Base for pakoras, kadhi, and sweets.",
    whySelected: "Not price-memorized — healthy markup.",
  }),
  staple({
    id: "rava-sooji-2kg",
    uuid: "b200000c-0000-4000-8000-00000000000c",
    name: "Rava / Sooji",
    shortDescription: "Semolina — 2 kg.",
    unit: "2 kg",
    cost: 4.5,
    rule: "margin",
    pricingRole: "margin",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Upma, halwa, and idli rava.",
    whySelected: "Not price-memorized — healthy markup.",
  }),
  staple({
    id: "turmeric-100g",
    uuid: "b200000d-0000-4000-8000-00000000000d",
    name: "Turmeric Powder",
    shortDescription: "Ground turmeric — 100 g.",
    unit: "100 g",
    cost: 2.5,
    rule: "margin-strong",
    pricingRole: "margin",
    collection: "spices",
    category: "Spices",
    roleLine: "Everyday haldi for dal and sabzi.",
    whySelected: "Classic margin zone — strong markup on single spices.",
  }),
  staple({
    id: "red-chilli-100g",
    uuid: "b200000e-0000-4000-8000-00000000000e",
    name: "Red Chilli Powder",
    shortDescription: "Ground red chilli — 100 g.",
    unit: "100 g",
    cost: 2.5,
    rule: "margin-strong",
    pricingRole: "margin",
    collection: "spices",
    category: "Spices",
    roleLine: "Heat and colour for everyday cooking.",
    whySelected: "Classic margin zone — strong markup on single spices.",
  }),
  staple({
    id: "cumin-100g",
    uuid: "b200000f-0000-4000-8000-00000000000f",
    name: "Cumin Powder",
    shortDescription: "Ground cumin — 100 g.",
    unit: "100 g",
    cost: 2.5,
    rule: "margin-strong",
    pricingRole: "margin",
    collection: "spices",
    category: "Spices",
    roleLine: "Jeera for tadka and everyday dishes.",
    whySelected: "Classic margin zone — strong markup on single spices.",
  }),
  staple({
    id: "coriander-100g",
    uuid: "b2000010-0000-4000-8000-000000000010",
    name: "Coriander Powder",
    shortDescription: "Ground coriander — 100 g.",
    unit: "100 g",
    cost: 2.5,
    rule: "margin-strong",
    pricingRole: "margin",
    collection: "spices",
    category: "Spices",
    roleLine: "Dhania for curries and marinades.",
    whySelected: "Classic margin zone — strong markup on single spices.",
  }),
  staple({
    id: "mdh-masala",
    uuid: "b2000011-0000-4000-8000-000000000011",
    name: "Badshah Punjabi Garam Masala",
    shortDescription: "Badshah Punjabi garam masala — 100 g.",
    brand: "Badshah",
    unit: "100 g",
    cost: EVEREST_UNIT_COSTS.badshahMasala100g,
    rule: "margin-strong",
    pricingRole: "margin",
    collection: "spices",
    category: "Spices",
    roleLine: "Brand-locked Punjabi garam masala.",
    whySelected: "Brand-locked blended masala — strong markup (Everest wholesale).",
  }),
  staple({
    id: "nanak-ghee",
    uuid: "b2000012-0000-4000-8000-000000000012",
    name: "Nanak Ghee",
    shortDescription: "Clarified butter — Nanak brand.",
    brand: "Nanak",
    unit: "750 ml",
    cost: 11.5,
    rule: "margin",
    pricingRole: "margin",
    collection: "dairy",
    category: "Dairy",
    roleLine: "Trusted ghee for roti and rice.",
    whySelected: "Trust item — healthy markup.",
  }),
  staple({
    id: "paneer",
    uuid: "b2000013-0000-4000-8000-000000000013",
    name: "Paneer",
    shortDescription: "Fresh Indian cottage cheese.",
    unit: "400 g",
    cost: 4.5,
    rule: "margin",
    pricingRole: "margin",
    collection: "dairy",
    category: "Dairy",
    roleLine: "Fresh paneer for curries and grills.",
    whySelected: "Fresh trust item — healthy markup.",
  }),
  staple({
    id: "dahi",
    uuid: "b2000014-0000-4000-8000-000000000014",
    name: "Dahi",
    shortDescription: "Fresh Indian-style yogurt.",
    unit: "750 g",
    cost: 3.5,
    rule: "margin",
    pricingRole: "margin",
    collection: "dairy",
    category: "Dairy",
    roleLine: "Everyday curd for raita and meals.",
    whySelected: "Fresh staple — healthy markup.",
  }),
  staple({
    id: "indian-pickle",
    uuid: "b2000015-0000-4000-8000-000000000015",
    name: "Indian Pickle",
    shortDescription: "Mixed vegetable achar.",
    unit: "500 g",
    cost: 4.0,
    rule: "margin-strong",
    pricingRole: "margin",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Side pickle for everyday meals.",
    whySelected: "Background item — strong markup.",
  }),
  staple({
    id: "makhana",
    uuid: "b2000016-0000-4000-8000-000000000016",
    name: "Makhana",
    shortDescription: "Fox nuts — plain roasted.",
    unit: "200 g",
    cost: 5.5,
    rule: "margin-strong",
    pricingRole: "margin",
    collection: "snacks",
    category: "Snacks",
    roleLine: "Light roasted snack — do not discount.",
    whySelected: "Strong markup item — don't discount.",
  }),
  staple({
    id: "poha",
    uuid: "b2000017-0000-4000-8000-000000000017",
    name: "Poha",
    shortDescription: "Flattened rice — thick.",
    unit: "2 lb",
    cost: 3.0,
    rule: "margin",
    pricingRole: "margin",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Quick breakfast poha.",
    whySelected: "Background staple — healthy markup.",
  }),
  staple({
    id: "red-label-tea",
    uuid: "b2000018-0000-4000-8000-000000000018",
    name: "Red Label Tea",
    shortDescription: "Brooke Bond Red Label tea.",
    brand: "Red Label",
    unit: "900 g",
    cost: EVEREST_UNIT_COSTS.redLabelTea900g,
    rule: "margin",
    pricingRole: "margin",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Brand-loyal everyday chai.",
    whySelected: "Brand-loyal tea — healthy markup.",
  }),
  staple({
    id: "maggi-noodles",
    uuid: "b2000019-0000-4000-8000-000000000019",
    name: "Maggi Masala Noodles",
    shortDescription: "Maggi 2-Minute Masala noodles — 280 g.",
    brand: "Maggi",
    unit: "280 g",
    cost: EVEREST_UNIT_COSTS.maggi280g,
    rule: "margin",
    pricingRole: "margin",
    collection: "snacks",
    category: "Snacks",
    roleLine: "Brand impulse snack.",
    whySelected: "Brand impulse item — healthy markup.",
  }),
  staple({
    id: "mustard-oil-1l",
    uuid: "b200001a-0000-4000-8000-00000000001a",
    name: "Mustard Oil",
    shortDescription: "Kachi ghani mustard oil — 1 L.",
    unit: "1 L",
    cost: EVEREST_UNIT_COSTS.mustardOil1L,
    rule: "margin-moderate",
    pricingRole: "margin",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Traditional cooking oil for tadka.",
    whySelected: "Some price-awareness — moderate markup.",
  }),
  staple({
    id: "sunflower-oil-1l",
    uuid: "b200001b-0000-4000-8000-00000000001b",
    name: "Sunflower Oil",
    shortDescription: "Refined sunflower oil — 1 L.",
    unit: "1 L",
    cost: 7.5,
    rule: "margin-moderate",
    pricingRole: "margin",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Neutral oil for everyday frying.",
    whySelected: "Some price-awareness — moderate markup.",
  }),
  staple({
    id: "salt-2kg",
    uuid: "b200001c-0000-4000-8000-00000000001c",
    name: "Salt",
    shortDescription: "Iodised salt — 2 kg.",
    unit: "2 kg",
    cost: 1.8,
    rule: "mild-kvi",
    pricingRole: "mild-kvi",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Cheap, mildly price-aware staple.",
    whySelected: "Cheap staple — mild KVI markup (~12%).",
    badges: ["Mild KVI"],
  }),
  staple({
    id: "sugar-2kg",
    uuid: "b200001d-0000-4000-8000-00000000001d",
    name: "Sugar",
    shortDescription: "Granulated sugar — 2 kg.",
    unit: "2 kg",
    cost: 1.8,
    rule: "mild-kvi",
    pricingRole: "mild-kvi",
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Cheap, mildly price-aware staple.",
    whySelected: "Cheap staple — mild KVI markup (~12%).",
    badges: ["Mild KVI"],
  }),
  staple({
    id: "lays-chips",
    uuid: "b200001e-0000-4000-8000-00000000001e",
    name: "Lays Magic Masala",
    shortDescription: "Lays Magic Masala potato chips.",
    brand: "Lays",
    unit: "52 g",
    cost: EVEREST_UNIT_COSTS.lays55g,
    rule: "margin",
    pricingRole: "margin",
    collection: "snacks",
    category: "Snacks",
    roleLine: "Impulse snack.",
    whySelected: "Impulse snack — healthy markup.",
  }),
  staple({
    id: "papad",
    uuid: "b200001f-0000-4000-8000-00000000001f",
    name: "Papad",
    shortDescription: "Roasted urad papad.",
    unit: "200 g",
    cost: 3.0,
    rule: "margin",
    pricingRole: "margin",
    collection: "snacks",
    category: "Snacks",
    roleLine: "Crispy side with meals.",
    whySelected: "Impulse side — healthy markup.",
  }),
  staple({
    id: "parle-g-biscuits",
    uuid: "b2000020-0000-4000-8000-000000000020",
    name: "Parle-G Biscuits",
    shortDescription: "Parle-G glucose biscuits.",
    brand: "Parle-G",
    unit: "800 g",
    cost: 1.5,
    rule: "margin",
    pricingRole: "margin",
    collection: "snacks",
    category: "Snacks",
    roleLine: "Classic tea-time biscuit.",
    whySelected: "Impulse snack — healthy markup.",
  }),
];
