import type { PantryProduct, PantryCollection } from "./pantry-catalog";
import { A1_UNIT_COSTS, EVEREST_UNIT_COSTS } from "./everest-wholesale";
import { CURATED_SHELF_IDS, type CuratedShelfId } from "./staple-shelf";
import { getGroupBuyTarget } from "./group-buy-config";
import { priceFromCost, pricingTierForProduct } from "./staple-pricing";

const PLACEHOLDER = "/products/staples/placeholder.svg";

type CompetitorEntry = {
  store: string;
  price: number;
  unit: string;
};

type StapleSpec = {
  id: string;
  uuid: string;
  name: string;
  shortDescription: string;
  brand?: string;
  unit: string;
  cost: number;
  pricingRole?: "kvi" | "margin";
  collection: PantryCollection;
  category: string;
  roleLine: string;
  whySelected: string;
  badges?: string[];
  competitors?: CompetitorEntry[];
  image?: string;
};

function staple(s: StapleSpec): PantryProduct {
  const tier = pricingTierForProduct(s.id);
  const pricing = priceFromCost(s.cost, tier);
  const image = s.image ?? PLACEHOLDER;
  const pricingRole = s.pricingRole ?? (tier === "kvi" ? "kvi" : "margin");
  return {
    uuid: s.uuid,
    id: s.id,
    slug: s.id,
    name: s.name,
    shortDescription: s.shortDescription,
    longDescription: s.shortDescription,
    category: s.category,
    collection: s.collection,
    image,
    imageAlt: s.name,
    unit: s.unit,
    stock: 50,
    groupBuyTarget: getGroupBuyTarget(s.id),
    ...pricing,
    competitors: s.competitors ?? [],
    brand: s.brand,
    origin: "India",
    pantry: {
      roleLine: s.roleLine,
      audience: [],
      badges: s.badges ?? [],
      whySelected: s.whySelected,
      pricingRole,
      ingredientSections: [{ rows: [{ name: "See package label" }] }],
      nutritionHighlights: "See package label.",
      preparation: "See package label.",
      storage: "Store in a cool, dry place.",
      countryOfOrigin: "India",
      gallery: s.image ? [s.image] : [PLACEHOLDER],
    },
  };
}

export const stapleProducts: PantryProduct[] = [
  staple({
    id: "aashirvaad-atta-20lb",
    image: "/products/staples/aashirvaad-atta-20lb.jpg",
    uuid: "b2000001-0000-4000-8000-000000000001",
    name: "Aashirvaad Atta",
    shortDescription: "Whole wheat atta — 20 lb bag.",
    brand: "Aashirvaad",
    unit: "20 lb",
    cost: 16.79,
    pricingRole: "kvi",
    collection: "staples",
    category: "Flour & grains",
    roleLine: "India's #1 atta — weekly roti staple.",
    whySelected: "Price-memorized atta — at wholesale, 0% markup.",
  }),
  staple({
    id: "basmati-rice-10lb",
    image: "/products/staples/basmati-rice-10lb.jpg",
    uuid: "b2000002-0000-4000-8000-000000000002",
    name: "Basmati Rice",
    shortDescription: "Premium branded basmati rice — 10 lb.",
    unit: "10 lb",
    cost: EVEREST_UNIT_COSTS.basmati10lb,
    pricingRole: "kvi",
    collection: "staples",
    category: "Flour & grains",
    roleLine: "Long-grain basmati for biryani and everyday meals.",
    whySelected: "Price-memorized rice — at wholesale, 0% markup.",
  }),
  staple({
    id: "sona-masoori-rice-10lb",
    image: "/products/staples/sona-masoori-rice-10lb.jpg",
    uuid: "b2000003-0000-4000-8000-000000000003",
    name: "Sona Masoori Rice",
    shortDescription: "Everyday sona masoori rice — 20 lb.",
    unit: "20 lb",
    cost: A1_UNIT_COSTS.sonaMasoori20lb,
    pricingRole: "kvi",
    collection: "staples",
    category: "Flour & grains",
    roleLine: "High-frequency everyday rice.",
    whySelected: "Everest Royal 20 lb — A1 ref $24.19 until distributor quote.",
  }),
  staple({
    id: "toor-dal-10lb",
    image: "/products/staples/toor-dal-10lb.jpg",
    uuid: "b2000004-0000-4000-8000-000000000004",
    name: "Toor Dal",
    shortDescription: "Split pigeon peas — 10 lb.",
    unit: "10 lb",
    cost: 18.19,
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Most-bought dal in Indian kitchens.",
    whySelected: "Most-bought dal — group-buy case pricing.",
  }),
  staple({
    id: "masoor-dal-10lb",
    image: "/products/staples/masoor-dal-10lb.jpg",
    uuid: "b2000005-0000-4000-8000-000000000005",
    name: "Masoor Dal",
    shortDescription: "Red lentils — 10 lb.",
    unit: "10 lb",
    cost: 8.29,
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Quick-cooking everyday dal.",
    whySelected: "Common household dal — group-buy case pricing.",
  }),
  staple({
    id: "urad-dal-10lb",
    image: "/products/staples/urad-dal-10lb.jpg",
    uuid: "b2000006-0000-4000-8000-000000000006",
    name: "Urad Dal",
    shortDescription: "Split black gram — 10 lb.",
    unit: "10 lb",
    cost: 14.99,
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Essential for dosa, idli, and dal makhani.",
    whySelected: "Background dal with healthy markup.",
  }),
  staple({
    id: "chana-dal-10lb",
    image: "/products/staples/chana-dal-10lb.jpg",
    uuid: "b2000007-0000-4000-8000-000000000007",
    name: "Chana Dal",
    shortDescription: "Split Bengal gram — 10 lb.",
    unit: "10 lb",
    cost: 12.29,
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Versatile dal for everyday cooking.",
    whySelected: "Background dal with healthy markup.",
  }),
  staple({
    id: "moong-dal-10lb",
    image: "/products/staples/moong-dal-10lb.jpg",
    uuid: "b2000008-0000-4000-8000-000000000008",
    name: "Moong Dal",
    shortDescription: "Split green gram — 10 lb.",
    unit: "10 lb",
    cost: 14.99,
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Light, easy-to-digest everyday dal.",
    whySelected: "Background dal with healthy markup.",
  }),
  staple({
    id: "rajma-10lb",
    image: "/products/staples/rajma-10lb.jpg",
    uuid: "b2000009-0000-4000-8000-000000000009",
    name: "Rajma",
    shortDescription: "Kidney beans — 10 lb.",
    unit: "10 lb",
    cost: 17.59,
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Classic rajma for Punjabi-style curries.",
    whySelected: "Background legume with healthy markup.",
  }),
  staple({
    id: "kabuli-chana-10lb",
    image: "/products/staples/kabuli-chana-10lb.jpg",
    uuid: "b200000a-0000-4000-8000-00000000000a",
    name: "Kabuli Chana",
    shortDescription: "Chickpeas — 10 lb.",
    unit: "10 lb",
    cost: 8.99,
    collection: "dal",
    category: "Dal & legumes",
    roleLine: "Chole and chaat staple.",
    whySelected: "Background legume with healthy markup.",
  }),
  staple({
    id: "besan-2kg",
    image: "/products/staples/besan-2kg.jpg",
    uuid: "b200000b-0000-4000-8000-00000000000b",
    name: "Besan",
    shortDescription: "Bambino gram flour — 2 kg.",
    unit: "2 kg",
    cost: 6.06,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Base for pakoras, kadhi, and sweets.",
    whySelected: "Everest Bambino 2 kg — provisional cost until quote.",
  }),
  staple({
    id: "rava-sooji-2kg",
    image: "/products/staples/rava-sooji-2kg.jpg",
    uuid: "b200000c-0000-4000-8000-00000000000c",
    name: "Rava / Sooji",
    shortDescription: "Bambino semolina — 2 kg.",
    unit: "2 kg",
    cost: 3.03,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Upma, halwa, and idli rava.",
    whySelected: "Everest Bambino 2 kg — provisional cost until quote.",
  }),
  staple({
    id: "turmeric-100g",
    image: "/products/staples/turmeric-100g.jpg",
    uuid: "b200000d-0000-4000-8000-00000000000d",
    name: "Turmeric Powder",
    shortDescription: "Apna ground turmeric (haldi) — 400 g.",
    brand: "Apna",
    unit: "400 g",
    cost: 4.49,
    collection: "spices",
    category: "Spices",
    roleLine: "Everyday haldi for dal and sabzi.",
    whySelected: "Apna haldi on A1 — MDH plain turmeric not listed.",
  }),
  staple({
    id: "red-chilli-100g",
    image: "/products/staples/red-chilli-100g.jpg",
    uuid: "b200000e-0000-4000-8000-00000000000e",
    name: "Red Chilli Powder",
    shortDescription: "Apna red chilli powder — 400 g.",
    brand: "Apna",
    unit: "400 g",
    cost: 4.99,
    collection: "spices",
    category: "Spices",
    roleLine: "Everyday mirch for heat and colour.",
    whySelected: "Apna mirch on A1 — Everest quote pending.",
  }),
  staple({
    id: "cumin-100g",
    image: "/products/staples/cumin-100g.jpg",
    uuid: "b200000f-0000-4000-8000-00000000000f",
    name: "Cumin Powder",
    shortDescription: "Apna ground cumin (jeera) — 400 g.",
    brand: "Apna",
    unit: "400 g",
    cost: 3.59,
    collection: "spices",
    category: "Spices",
    roleLine: "Jeera for tadka and everyday dishes.",
    whySelected: "Apna jeera on A1 — MDH plain cumin not listed.",
  }),
  staple({
    id: "coriander-100g",
    image: "/products/staples/coriander-100g.jpg",
    uuid: "b2000010-0000-4000-8000-000000000010",
    name: "Coriander Powder",
    shortDescription: "Apna ground coriander (dhania) — 400 g.",
    brand: "Apna",
    unit: "400 g",
    cost: 2.79,
    collection: "spices",
    category: "Spices",
    roleLine: "Dhania for curries and marinades.",
    whySelected: "Apna dhania on A1 — MDH plain coriander not listed.",
  }),
  staple({
    id: "mdh-masala",
    image: "/products/staples/mdh-masala.jpg",
    uuid: "b2000011-0000-4000-8000-000000000011",
    name: "MDH Kitchen King",
    shortDescription: "MDH Kitchen King masala — 100 g.",
    brand: "MDH",
    unit: "100 g",
    cost: 2.15,
    collection: "spices",
    category: "Spices",
    roleLine: "Brand-locked blended masala.",
    whySelected: "MDH Kitchen King on A1 — $21.49/case × 10.",
  }),
  staple({
    id: "nanak-ghee",
    image: "/products/staples/nanak-ghee.jpg",
    uuid: "b2000012-0000-4000-8000-000000000012",
    name: "Nanak Ghee",
    shortDescription: "Clarified butter — 1.6 kg tub.",
    brand: "Nanak",
    unit: "1.6 kg",
    cost: A1_UNIT_COSTS.nanakGhee1_6kg,
    collection: "dairy",
    category: "Dairy",
    roleLine: "Trusted ghee for roti and rice.",
    whySelected: "Nanak ghee — A1 ref until Everest quote.",
  }),
  staple({
    id: "paneer",
    image: "/products/staples/paneer.jpg",
    uuid: "b2000013-0000-4000-8000-000000000013",
    name: "Paneer",
    shortDescription: "Fresh Indian cottage cheese — 1.6 kg.",
    unit: "1.6 kg",
    cost: A1_UNIT_COSTS.nanakPaneer1_6kg,
    collection: "dairy",
    category: "Dairy",
    roleLine: "Fresh paneer for curries and grills.",
    whySelected: "Nanak paneer — A1 ref until Everest quote.",
  }),
  staple({
    id: "dahi",
    image: "/products/staples/dahi.jpg",
    uuid: "b2000014-0000-4000-8000-000000000014",
    name: "Dahi",
    shortDescription: "Fresh Indian-style yogurt — 1.8 kg.",
    unit: "1.8 kg",
    cost: 3.5,
    collection: "dairy",
    category: "Dairy",
    roleLine: "Everyday curd for raita and meals.",
    whySelected: "Fresh staple — healthy markup.",
  }),
  staple({
    id: "indian-pickle",
    image: "/products/staples/indian-pickle.jpg",
    uuid: "b2000015-0000-4000-8000-000000000015",
    name: "Indian Pickle",
    shortDescription: "Mixed vegetable achar — 2.27 kg jar.",
    unit: "2.27 kg",
    cost: 4.0,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Side pickle for everyday meals.",
    whySelected: "Background item — strong markup.",
  }),
  staple({
    id: "makhana",
    image: "/products/staples/makhana.jpg",
    uuid: "b2000016-0000-4000-8000-000000000016",
    name: "Makhana",
    shortDescription: "Fox nuts — plain roasted, 2 lb.",
    unit: "2 lb",
    cost: 5.5,
    collection: "snacks",
    category: "Snacks",
    roleLine: "Light roasted snack — do not discount.",
    whySelected: "Strong markup item — don't discount.",
  }),
  staple({
    id: "poha",
    image: "/products/staples/poha.jpg",
    uuid: "b2000017-0000-4000-8000-000000000017",
    name: "Poha",
    shortDescription: "Flattened rice — thin poha, 4 lb.",
    unit: "4 lb",
    cost: 3.0,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Quick breakfast poha.",
    whySelected: "Background staple — healthy markup.",
  }),
  staple({
    id: "red-label-tea",
    image: "/products/staples/red-label-tea.jpg",
    uuid: "b2000018-0000-4000-8000-000000000018",
    name: "Red Label Tea",
    shortDescription: "Brooke Bond Red Label tea.",
    brand: "Red Label",
    unit: "900 g",
    cost: EVEREST_UNIT_COSTS.redLabelTea900g,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Brand-loyal everyday chai.",
    whySelected: "Brand-loyal tea — healthy markup.",
  }),
  staple({
    id: "maggi-noodles",
    image: "/products/staples/maggi-noodles.jpg",
    uuid: "b2000019-0000-4000-8000-000000000019",
    name: "Maggi Noodles",
    shortDescription: "Maggi 2-Minute Masala noodles — 4-pack (280 g).",
    brand: "Maggi",
    unit: "4-pack (280 g)",
    cost: EVEREST_UNIT_COSTS.maggi280g,
    collection: "snacks",
    category: "Snacks",
    roleLine: "Brand impulse snack.",
    whySelected: "Brand impulse item — healthy markup.",
  }),
  staple({
    id: "mustard-oil-1l",
    image: "/products/staples/mustard-oil-1l.jpg",
    uuid: "b200001a-0000-4000-8000-00000000001a",
    name: "Mustard Oil",
    shortDescription: "Apna kachi ghani mustard oil — 1 L.",
    brand: "Apna",
    unit: "1 L",
    cost: A1_UNIT_COSTS.mustardOil1L,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Traditional cooking oil for tadka.",
    whySelected: "Apna 1 L on A1 — cheaper than Tez Everest case.",
  }),
  staple({
    id: "sunflower-oil-1l",
    image: "/products/staples/sunflower-oil-1l.jpg",
    uuid: "b200001b-0000-4000-8000-00000000001b",
    name: "Sunflower Oil",
    shortDescription: "Refined sunflower oil — 3 L.",
    unit: "3 L",
    cost: 7.5,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Neutral oil for everyday frying.",
    whySelected: "Some price-awareness — moderate markup.",
  }),
  staple({
    id: "salt-2kg",
    image: "/products/staples/salt-2kg.jpg",
    uuid: "b200001c-0000-4000-8000-00000000001c",
    name: "Salt",
    shortDescription: "Iodised table salt — 1 kg.",
    unit: "1 kg",
    cost: A1_UNIT_COSTS.salt1kg,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Cheap everyday staple.",
    whySelected: "Windsor salt on A1 — Everest PK quote pending.",
  }),
  staple({
    id: "sugar-2kg",
    image: "/products/staples/sugar-2kg.jpg",
    uuid: "b200001d-0000-4000-8000-00000000001d",
    name: "Sugar",
    shortDescription: "Granulated sugar — 2 kg.",
    unit: "2 kg",
    cost: A1_UNIT_COSTS.sugar2kg,
    collection: "cooking",
    category: "Cooking essentials",
    roleLine: "Cheap everyday staple.",
    whySelected: "Redpath sugar on A1 — Everest PK quote pending.",
  }),
  staple({
    id: "lays-chips",
    image: "/products/staples/lays-chips.jpg",
    uuid: "b200001e-0000-4000-8000-00000000001e",
    name: "Lays Magic Masala",
    shortDescription: "Lays Magic Masala chips — 50–55 g pack.",
    brand: "Lays",
    unit: "50–55 g",
    cost: EVEREST_UNIT_COSTS.lays55g,
    collection: "snacks",
    category: "Snacks",
    roleLine: "Impulse snack.",
    whySelected: "Everest case 70 × 50–55 g @ $54 → $0.77/pack cost.",
  }),
  staple({
    id: "papad",
    image: "/products/staples/papad.jpg",
    uuid: "b200001f-0000-4000-8000-00000000001f",
    name: "Papad",
    shortDescription: "Roasted urad papad.",
    unit: "200 g",
    cost: 3.0,
    collection: "snacks",
    category: "Snacks",
    roleLine: "Crispy side with meals.",
    whySelected: "Impulse side — healthy markup.",
  }),
  staple({
    id: "parle-g-biscuits",
    image: "/products/staples/parle-g-biscuits.jpg",
    uuid: "b2000020-0000-4000-8000-000000000020",
    name: "Parle-G Biscuits",
    shortDescription: "Parle-G glucose biscuits.",
    brand: "Parle-G",
    unit: "800 g",
    cost: 1.5,
    collection: "snacks",
    category: "Snacks",
    roleLine: "Classic tea-time biscuit.",
    whySelected: "Impulse snack — healthy markup.",
  }),
];

if (stapleProducts.length !== CURATED_SHELF_IDS.length) {
  throw new Error(
    `staple catalog must have ${CURATED_SHELF_IDS.length} SKUs, got ${stapleProducts.length}`,
  );
}
const shelfIdSet = new Set(CURATED_SHELF_IDS);
for (const p of stapleProducts) {
  if (!shelfIdSet.has(p.id as CuratedShelfId)) {
    throw new Error(`unexpected staple SKU on shelf: ${p.id}`);
  }
}
